name: CI/CD for WordPress

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER_USERNAME: 'bucaothu'
  DOCKER_PASSWORD: 'Fuckyoustoler12'
  MYSQL_HOST: 'mysql_db:3306'
  MYSQL_USER: 'wordpress_user'
  MYSQL_PASSWORD: '270701'
  MYSQL_ROOT_PASSWORD: 'root'
  MYSQL_DATABASE: 'wordpress'




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os-buildx-${{ github.sha
          restore-keys: |
            ${{ runner.os-buildx-

      - name: Debug Docker username
        run: echo $DOCKER_USERNAME


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./wordpress
          push: true
          tags: dinhhongkong/demo_wordpress_cicd:latest

      - name: Set up environment variables
        run: |
          echo "MYSQL_HOST=$MYSQL_HOST"
          echo "MYSQL_USER=$MYSQL_USER"
          echo "MYSQL_PASSWORD=$MYSQL_PASSWORD"
          echo "MYSQL_DATABASE=$MYSQL_DATABASE"
          echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: sleep 60

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
